[package]
name = "path-tracer"
version = "0.1.0"
authors = ["Frederic Merizen <frederic.merizen@gmail.com>"]
edition = "2018"

[dependencies]
assert_approx_eq = "1.1.0"
image = "*"
itertools = "0.8"
lazy_static = "1.3.*"
rand = "0.6"
rayon = "1.0"
regex = "1"
